### ISSUE TITLE
Doesn't seem to be working with iPadOS 17

### ISSUE THREAD

**Issue by simplyinquisitive** [ykicisk/PdfMarginAdjusterDoc#5]
The app does nothing when I click the save/share button after setting the margins. It was working fine on iPadOS 16 till yesterday.

**Comment by ZHIHA0** [comment]
I can confirm this issue. The app is not working with iPadOS 17.

**Comment by simplyinquisitive** [comment]
> I can confirm this issue. The app is not working with iPadOS 17.

as a workaround for now, I wrote a python script to add margins https://github.com/simplyinquisitive/AddMargin2PDF

**Comment by ZHIHA0** [comment]
Thank you for your effort! I will try to run it, I'm not

**Comment by ZHIHA0** [comment]
-

**Comment by rocketspeeder69** [comment]
このアプリ、ipadで便利に使わせて頂いています。ありがとうございます。
私もiOS17にアップグレードしてから、アプリから保存/共有ボタンを押しても何も反応しなくなり、
アウトプット出来なくなって困っています。

正確には、ボタンを押すと、アプリ全体の表示が薄くなり、再度ボタンを押すと、アプリの濃度は戻りますが、
再度ボタンを押すとまた濃度が薄くなりるのみで保存/共有画面に遷移しません。

こちらiOSが原因と思われますが、対応お願いできるととっても助かります。

**Comment by fatedyang** [comment]
> The app does nothing when I click the save/share button after setting the margins. It was working fine on iPadOS 16 till yesterday.

Hi, may ik how to fix this issue? I’m facing the same problem as well. I can’t export files out from the app

**Comment by dreamacodes** [comment]
I have the same issue :(

I would pay to make this work x.x

**Comment by simplyinquisitive** [comment]
> > The app does nothing when I click the save/share button after setting the margins. It was working fine on iPadOS 16 till yesterday.
> 
> Hi, may ik how to fix this issue? I’m facing the same problem as well. I can’t export files out from the app

As a workaround, [refer to my comment above if you have Python installed on your system](https://github.com/ykicisk/PdfMarginAdjusterDoc/issues/5#issuecomment-1730800908)

**Comment by abhijeetgaiha** [comment]
Same here. The export button doesn't work on iPadOS 17.

**Comment by ysetou** [comment]
> > I can confirm this issue. The app is not working with iPadOS 17.
> 
> as a workaround for now, I wrote a python script to add margins https://github.com/simplyinquisitive/AddMargin2PDF

下記の内容にすると、アプリと大体同じになるかもです。

    #specify margins here
    left_margin = 0*25 
    right_margin = 6*50
    top_margin = -1*25
    bottom_margin = -1*25

**Comment by ykicisk** [comment]
皆様、情報共有ありがとうございます。
本アプリの開発者です。

こちらのissue見逃しておりました、、、申し訳有りません 🙇 
早急に確認いたしますので、しばらくお待ち下さい。

---

This is developer for this App.

I'm sorry for the late reply 🙇 
I will check the problem as soon as possible.

**Comment by ykicisk** [comment]
私もこの問題を再現することができました。
残念ながら、私のMacが非常に古い機種（MacBook Pro  Retina, 13-inch, Early 2015）なので、iPadOS 17をサポートするXCode 15をインストールできないようです 😭

回避策がないか調べますが、問題の解決に非常に時間がかかると思います。
本当に申し訳有りませんが、よろしくお願いいたします。

---

I was also able to reproduce this issue.
Unfortunately, my Mac is very old (MacBook Pro Retina, 13-inch, Early 2015). So I CAN'T install XCode 15 which supports iPadOS 17.😭

I will look into a workaround, but I think it take a very long time to resolve the issue.
I apologize for the inconvenience and thank you in advance for your patience.

**Comment by abhijeetgaiha** [comment]
> 私もこの問題を再現することができました。 残念ながら、私のMacが非常に古い機種（MacBook Pro Retina, 13-inch, Early 2015）なので、iPadOS 17をサポートするXCode 15をインストールできないようです 😭
> 
> 回避策がないか調べますが、問題の解決に非常に時間がかかると思います。 本当に申し訳有りませんが、よろしくお願いいたします。
> 
> I was also able to reproduce this issue. Unfortunately, my Mac is very old (MacBook Pro Retina, 13-inch, Early 2015). So I CAN'T install XCode 15 which supports iPadOS 17.😭
> 
> I will look into a workaround, but I think it take a very long time to resolve the issue. I apologize for the inconvenience and thank you in advance for your patience.

Would you consider open sourcing it? Maybe someone else can help.

**Comment by ykicisk** [comment]
@abhijeetgaiha 

Thank you for your suggestion.
I think it is the last option because my source code is too poor to be made public. 😅

I have good news and bad news.

The good news is that I succeeded in installing MacOS Ventura on my Mac with a trick.
I might continue to develop this App.🎉

The bad news is that I lost the latest source code for this App.😵
So, I will revert this App to version 1.3.4 and fix the problem.
The help window will be downgraded, but it's not a serious problem.

**Comment by ykicisk** [comment]
@simplyinquisitive @ZHIHA0 @rocketspeeder69 @fatedyang @dreamacodes @abhijeetgaiha @ysetou 
I have just released version 1.3.6, which fixes this bug.
I hope you will check it out!

I apologize for the delay.

**Comment by ysetou** [comment]
さきほど、動作確認をいたしました。問題無く動作しています。
ご対応ありがとうございました。

**Comment by abhijeetgaiha** [comment]
Thank you for the update!
